services:
  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: yarn run start:dev
    env_file:
      - ./apps/users/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
#   postgres:
#     image: postgres
#     restart: always
#     env_file: 
#       - .env
#     ports:
#       - '5432:5432'
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
# volumes:
#   postgres-data: