apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: users
spec:
  rules:
    - http:
        paths:
          - path: /users/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: users
                port:
                  number: 3000